### ISSUE TITLE
article 22 Error in Windows 64-bit platform

### ISSUE THREAD

**Issue by Saeid2016** [delphidabbler/articles#1]
Hi, All codes described in article 22 works in Windows 32-bit platform but it gives an error in 64-bit platform.
the following code causes the error:
fContainer := TExternalContainer.Create(WebBrowser1);

[Screenshot1](<a href="https://uupload.ir/view/error1_5mnr.png" target="_blank"><img src="https://s6.uupload.ir/files/error1_5mnr_thumb.png" border="0" alt="آپلود عکس" /></a>) 

[Screenshot2](<a href="https://uupload.ir/view/error2_n79b.png" target="_blank"><img src="https://s6.uupload.ir/files/error2_n79b_thumb.png" border="0" alt="آپلود عکس" /></a>)

**Comment by delphidabbler** [comment]
Thanks for reporting this. I'll take a look.

**Comment by delphidabbler** [comment]
I've just downloaded and compiled the demo program that comes with article #22, and that compiles OK with Delphi 11.0 in both 32 bit and 64 bit.

So now I'm going to compare that code with that in the article to see if there's a difference.

**Comment by delphidabbler** [comment]
1st step is to convert the article to HTML - about time really!

**Comment by delphidabbler** [comment]
Hi @Saeid2016 

Which version of Delphi were you using please?

I'm a bit baffled by the call into _TCustomEdgeBrowser_.

**Comment by delphidabbler** [comment]
@Saeid2016

I've now created a project from scratch using the instructions and code presented in the article and I've successfully compiled the program with Delphi 11.0 as both a 32 bit and a 64 bit target. The same goes for the code from the `delphidabbler/article-demos` project, in the `article-22` folder.

Just checking if you were using an old style _TWebBrowser_ or the newer _TEdgeBrowser_, because the article and code expects a _TWebBrowser_ to be used.

If that's not the reason for the error then I'm baffled!

**Comment by delphidabbler** [comment]
Here's a zip file containing the project that worked for me with Delphi 11.0 as a 64 bit target:

* [Article22.zip](https://github.com/delphidabbler/articles/files/8886137/Article22.zip)

I'd be interested to know if that works for you.

**Comment by Saeid2016** [comment]
> @Saeid2016
> 
> I've now created a project from scratch using the instructions and code presented in the article and I've successfully compiled the program with Delphi 11.0 as both a 32 bit and a 64 bit target. The same goes for the code from the `delphidabbler/article-demos` project, in the `article-22` folder.
> 
> Just checking if you were using an old style _TWebBrowser_ or the newer _TEdgeBrowser_, because the article and code expects a _TWebBrowser_ to be used.
> 
> If that's not the reason for the error then I'm baffled!

Hi @delphidabbler and thank you for replay.
I use Delphi 10.4. I have used TEmbeddedWB instead TWebBrowser. So already I had used this code to create a instance of TExternalContainer:
`fContainer := TExternalContainer.Create(TWebBrowser(EmbeddedWB1));`

Then I changed the HostedBrowser type to TEmbeddedWB and now it works correctly. now it gives the error only in debug mode but in release mode there are no error.

I have another question. like Chrome and Firefox browsers, my browser in a TFrame that is created by end user several times and in each time the TExternalContainer is created by the above code. My question is that how I free the fContainer when the user closes the tab of PageControl to prevent from memory leak?

**Comment by delphidabbler** [comment]
> 
Glad things are working now.

> I have another question ... my browser is in a TFrame that is created by end user several times and in each time the TExternalContainer is created by the above code. My question is that how I free the fContainer when the user closes the tab of PageControl to prevent from memory leak?

Do you create your TExternalContainer in the TFrame constructor? If so you can free it in the TFrame destructor. But I guess it's not that simple.

Can you get a notification when the user closes a frame by handling an event of TPageControl? I can't recall if TPageControl has an event that is fired when a tab gets deleted and I'm not at my PC just now so I can't check. But if it does you might be able to free TExternalContainer by handling such an event.

One final thought: can you wrap each TExternalContainer object in a class that descends from TInterfacedObject and store a reference to an interface to the wrapper. That way 
the interface object will be freed when it goes out of scope and you can implement the interfaced class destructor to free the TExternalContainer object it wraps.

Without seeing your source I don't know if any of these suggestions will work

**Comment by Saeid2016** [comment]
> Do you create your TExternalContainer in the TFrame constructor? If so you can free it in the TFrame destructor. But I guess it's not that simple.
> 
No, I have defined fcontainer in main form variables and I create the TExternalContainer in main form.

> Can you get a notification when the user closes a frame by handling an event of TPageControl?
>
My page control component is TsPageControl (from [AlphaSkins)](https://www.alphaskins.com/) which has OnCloseBtnClick. It fires when user clicks on close button of tab. In this event I free the frame an all objects I created in tab. But I don't know how I free the TExternalContainer in this event.

> One final thought: can you wrap each TExternalContainer object in a class that descends from TInterfacedObject and store a reference to an interface to the wrapper. That way
the interface object will be freed when it goes out of scope and you can implement the interfaced class destructor to free the TExternalContainer object it wraps.
>
Is it possible to give me a source code for this?

**Comment by delphidabbler** [comment]
@Saeid2016 

> No, I have defined fcontainer in main form variables and I create the TExternalContainer in main form.

> My page control component is TsPageControl (from AlphaSkins) which has OnCloseBtnClick event. It fires when user clicks on close button of tab. In this event I free the frame and all objects I created in page. But I don't know how I free the TExternalContainer in this event.

Somehow you have to create a  map between each new page control tab and the TExternalContainer instance that hosts the browser control on that new tab.

Then, when you handle the OnCloseBtnClick event, which I assume is in the main form, you need to look up the correct TExternalContainer instance and free it. It's also important you free it before the browser control gets freed.

Sorry this is a bit vague, but I'm really struggling to visualise your code. If you could post some snippets of that show how you create a new tab / frame, how you record the different TExternalContainer instances and how you tidy up in OnCloseBtnClick I _might_ be able to be more helpful. 

> Is it possible to give me a sample code for this?

Yes, but from what you've now told me, I now doubt it will work for you. Anyhow, here we go - this code is untested as I'm typing it on my Android tablet! 

```pascal
type
  TBox = class(TInterfacedObject, IInterface)
  private
    FObj: TExternalContainer;
  public
    constructor Create(Obj: TExternalContainer);
    destructor Destroy; override;
  end;

constructor TBox.Create(Obj: TExternalContainer)
begin
  inherited Create;
  Fobj := Obj;
end;

destructor TBox.Destroy;
begin
  FObj.Free;
  inherited;
end;
```
To use this, declare a variable, say `v`, of type IInterface and do `v := TBox.Create(e)` , where `e` is a TExternalContainer instance.  When `v` goes out of scope Delphi will free it and `v` will free `e` in the TBox destructor. 

The reason I am not sure this will work for you if you are recording the TExternalContainer instances in the form is that any replacement TBox objects may stay in scope for the lifetime of your main form and so won't free the boxed TExternalContainer. It all depends how you're storing the TExternalContainer instances.

Cheers 
Peter

**Comment by Saeid2016** [comment]
Hi @delphidabbler 
> Sorry this is a bit vague, but I'm really struggling to visualise your code. If you could post some snippets of that show how you create a new tab / frame, how you record the different TExternalContainer instances and how you tidy up in OnCloseBtnClick I might be able to be more helpful.
>

I edited the Arcicle22 sample. Please see it and help me how to free the fcontainer when user closes the TsPageControl tab.
[NewArticle22](https://filelu.com/5og92stueg7y)

**Comment by delphidabbler** [comment]
@Saeid2016 

Hi

Sorry it's been a while - my Internet has been down.

I've had a look at the code & I think I see the problem. 

When you create a tab & frame after the first one you are creating a new TExternalContainer and storing it in fContainer. By doing that you overwrite the TExternalContainer instance you already stored in fContainer when the previous frame was created.

That's your memory leak. You need to keep a reference to each instance of TExternalContainer you create so they can be freed. In fact you need to free the correct TExternalContainer object for the frame you are closing. 

There are two options:

1. Create a collection of TExternalContainer objects in the main form and somehow keep mapping between the frames and the TExternalContainer objects that relate to them, because you need to free the correct TExternalContainer when you free the frame. I'd do that using a TDictionary<TFrame, TExternalContainer> object. But it's still a bit complicated. 

2. ***Much*** simpler:  create the TExternalContainer object in the TFrame constructor and free it in the destructor, and get rid of the fContainer field. 

I would recommend the 2nd approach. If you go with it, here's some outline code that might help.

> ***Warning:*** I have typed all this on my tablet late at night and haven't tested it or even compiled it & it's likely you'll have to tweak it!

## Unit2

```pascal
type
  TFrame2 = class(TFrame)
    WebBrowser1: TWebBrowser;
  private
    fContainer: TExternalContainer;
  public
    constructor Create(AOwner: TComponent); override;
    destructor Destroy; override; 
  end;

...

constructor TFrame2.Create(AOwner: TComponent); override;
begin
  inherited Create(AOwner);
  fContainer := TExternalContainer.Create(WebBrowser1);
end;

destructor TFrame2.Destroy; override; 
begin
  fContainer.Free;
  inherited  Destroy;
end;
```

## Unit1

* Remove `fContainer := TExternalContainer.Create(tmpframe.WebBrowser1);` from `TForm1.CreateFrame`.
* Remove the `fContainer` field from the form. 

Now, when you create the frame the TExternalContainer object will be created automatically and when you free the frame in `TForm1.pgcntrl1CloseBtnClick`, the frame will free the TExternalContainer as it gets destroyed.

## Optional property in Unit2

If you need to access your TExternalContainer objects just expose them as a property of the frame like this:

```pascal
type
  TFrame2 = class(TFrame)
  ...
  public
    ...
    property Container: TExternalContainer read fContainer;
    ...
  end;
```
If you don't need the property then my suggested method means that once you update Unit2 you can forget all about managing your numerous TExternalContainer objects.

----

I hope that works. I have used a very similar approach in my [CodeSnip program](https://delphidabbler.com/software/codesnip).

**Comment by Saeid2016** [comment]
Hi @delphidabbler 
I edited my code and now it works without any memory leak. Thank you very very much.

**Comment by delphidabbler** [comment]
Hi @Saeid2016

Great. Glad it worked. I quite enjoyed tracking down the problem because I had not even looked at that code for several years!

Regards
Peter
